//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOMPO
    {
        #region Primitive Properties
    
        public virtual string PONUMBER
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLPO
        {
            get;
            set;
        }
    
        public virtual string PRNUMBERSAP
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGAOPTIONAL
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLKIRIMCABVENDOR
        {
            get;
            set;
        }
    
        public virtual string KETPO
        {
            get;
            set;
        }
    
        public virtual string PPNOPTIONAL
        {
            get;
            set;
        }
    
        public virtual string CABANGVENDOR
        {
            get;
            set;
        }
    
        public virtual string DESCCHANGEPO
        {
            get;
            set;
        }
    
        public virtual string DESCPO
        {
            get;
            set;
        }
    
        public virtual Nullable<double> DISC
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGABBN
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGADPP
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGAPPNUNIT
        {
            get;
            set;
        }
    
        public virtual string MAINTYPEUNIT
        {
            get;
            set;
        }
    
        public virtual Nullable<double> PRICELIST
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PROMISEDLVDATEPO
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLCHANGEPO
        {
            get;
            set;
        }
    
        public virtual string VENDORID
        {
            get;
            set;
        }
    
        public virtual string VENDORNAME
        {
            get;
            set;
        }
    
        public virtual Nullable<double> BIAYAPENGIRIMAN
        {
            get;
            set;
        }
    
        public virtual string CITY
        {
            get;
            set;
        }
    
        public virtual string BENTUKAKHIRUNIT
        {
            get;
            set;
        }
    
        public virtual string HISTORYPO
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLMASUKKAROSERI
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSELESAIKAROSERI
        {
            get;
            set;
        }
    
        public virtual string PURCHASESTATUS
        {
            get;
            set;
        }
    
        public virtual string POSTATUSID
        {
            get;
            set;
        }
    
        public virtual Nullable<double> ONTHEROADPRICE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EXPECTEDDATEDELIVERED
        {
            get;
            set;
        }
    
        public virtual string COLOR
        {
            get;
            set;
        }
    
        public virtual string UNITDELIVERYADDRESS
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALDATEDELIVEREDUNIT
        {
            get;
            set;
        }
    
        public virtual string REMARKSPOVENDOR
        {
            get;
            set;
        }
    
        public virtual string REMARKSCARROSSERIE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDBPKBHOFROMBRANCH
        {
            get;
            set;
        }
    
        public virtual Nullable<double> DELIVERYCOST
        {
            get;
            set;
        }
    
        public virtual string CARROSERIEVENDORNAME
        {
            get;
            set;
        }
    
        public virtual string ACCESORIESADDRESS
        {
            get;
            set;
        }
    
        public virtual string REMARKS
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DODATE
        {
            get;
            set;
        }
    
        public virtual string DONUMBER
        {
            get;
            set;
        }
    
        public virtual string MODIFIED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGABBN_INPUT
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGADPP_INPUT
        {
            get;
            set;
        }
    
        public virtual Nullable<double> HARGAPPNUNIT_INPUT
        {
            get;
            set;
        }
    
        public virtual string CARMODEL
        {
            get;
            set;
        }
    
        public virtual string CARSERIES
        {
            get;
            set;
        }
    
        public virtual string COMPANYCODE
        {
            get;
            set;
        }
    
        public virtual string COMPANYNAME
        {
            get;
            set;
        }
    
        public virtual string ATMT
        {
            get;
            set;
        }
    
        public virtual string KODECABANG
        {
            get;
            set;
        }
    
        public virtual string CABANGTRAC
        {
            get;
            set;
        }
    
        public virtual string MERK
        {
            get;
            set;
        }
    
        public virtual string TYPEUNIT
        {
            get;
            set;
        }
    
        public virtual string VARIAN
        {
            get;
            set;
        }
    
        public virtual string VARIAN_INPUT
        {
            get;
            set;
        }
    
        public virtual string MERK_INPUT
        {
            get;
            set;
        }
    
        public virtual Nullable<int> POQTY
        {
            get;
            set;
        }
    
        public virtual string PRSAP
        {
            get;
            set;
        }
    
        public virtual string REASONREVISEDBYVENDOR
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> REVISEDDATE
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> isRevised
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLGI
        {
            get;
            set;
        }
    
        public virtual string RefDocNo
        {
            get;
            set;
        }
    
        public virtual string CODEGROUP
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> TOTALPAYMENT
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> LOCALPRICE
        {
            get;
            set;
        }
    
        public virtual string CURRENCY
        {
            get;
            set;
        }
    
        public virtual string CLIENT
        {
            get;
            set;
        }
    
        public virtual string FISCALYEAR
        {
            get;
            set;
        }
    
        public virtual string PROPOSALNUMBER
        {
            get;
            set;
        }
    
        public virtual string ITEM
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> APPROVALDATETIME
        {
            get;
            set;
        }
    
        public virtual Nullable<int> flagRejection
        {
            get;
            set;
        }
    
        public virtual string PICKAROSERI
        {
            get;
            set;
        }
    
        public virtual string NOTELEPONKAROSERI
        {
            get;
            set;
        }
    
        public virtual string BENTUKKAROSERI
        {
            get;
            set;
        }
    
        public virtual string SHIPPINGADDRESS1
        {
            get;
            set;
        }
    
        public virtual string SHIPPINGADDRESS2
        {
            get;
            set;
        }
    
        public virtual string SHIPPINGADDRESS3
        {
            get;
            set;
        }
    
        public virtual string SHIPPINGADDRESS4
        {
            get;
            set;
        }
    
        public virtual string BBNADDRESS1
        {
            get;
            set;
        }
    
        public virtual string BBNADDRESS2
        {
            get;
            set;
        }
    
        public virtual string BBNADDRESS3
        {
            get;
            set;
        }
    
        public virtual string BBNADDRESS4
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlModifiedDate
        {
            get;
            set;
        }
    
        public virtual string xmlModifiedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlCreatedDate
        {
            get;
            set;
        }
    
        public virtual string xmlCreatedBy
        {
            get;
            set;
        }
    
        public virtual string xmlStatus
        {
            get;
            set;
        }
    
        public virtual string updateqty
        {
            get;
            set;
        }

        #endregion

    }
}
