//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOMIR
    {
        #region Primitive Properties
    
        public virtual string PONUMBER
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDINV
        {
            get;
            set;
        }
    
        public virtual string HARGADELIVERYAP
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> INVDATE
        {
            get;
            set;
        }
    
        public virtual string INVNO
        {
            get;
            set;
        }
    
        public virtual string KETBAYAR
        {
            get;
            set;
        }
    
        public virtual string NOFAKTURPAJAK
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSERAHTAGIHAN
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TERMOFPAYMENT
        {
            get;
            set;
        }
    
        public virtual string NOAP
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLPEMBAYARAN
        {
            get;
            set;
        }
    
        public virtual string KETTAGIHAN
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ESTIMATEDPAYMENTDATE
        {
            get;
            set;
        }
    
        public virtual string INVOICESTATUS
        {
            get;
            set;
        }
    
        public virtual string REASONREJECTIONINVOICE
        {
            get;
            set;
        }
    
        public virtual string BPHNUMBER
        {
            get;
            set;
        }
    
        public virtual string MODIFIED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> REVISEDATE
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> isRevised
        {
            get;
            set;
        }
    
        public virtual string xmlStatus
        {
            get;
            set;
        }
    
        public virtual string xmlCreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlCreatedDate
        {
            get;
            set;
        }
    
        public virtual string xmlModifiedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlModifiedDateInvNo
        {
            get;
            set;
        }
    
        public virtual string xmlModifiedByInvNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlCreatedDateInvNo
        {
            get;
            set;
        }
    
        public virtual string xmlCreatedByInvNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlModifiedDateFaktur
        {
            get;
            set;
        }
    
        public virtual string xmlModifiedByFaktur
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlCreatedDateFaktur
        {
            get;
            set;
        }
    
        public virtual string xmlCreatedByFaktur
        {
            get;
            set;
        }
    
        public virtual string xmlStatusInvNo
        {
            get;
            set;
        }
    
        public virtual string xmlStatusByEngine
        {
            get;
            set;
        }

        #endregion

    }
}
