//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOMPROPOSALPAYMENT
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string ProposalNumber
        {
            get;
            set;
        }
    
        public virtual string CompCode
        {
            get;
            set;
        }
    
        public virtual string Year
        {
            get;
            set;
        }
    
        public virtual string DocumentNumber
        {
            get;
            set;
        }
    
        public virtual string PurchaseDocument
        {
            get;
            set;
        }
    
        public virtual string Item
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ApproveDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.TimeSpan> ApproveTime
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> Status
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        public virtual string CreateBy
        {
            get;
            set;
        }

        #endregion

    }
}
