//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02005_TEMP_IS
    {
        #region Primitive Properties
    
        public virtual string GroupingCode
        {
            get;
            set;
        }
    
        public virtual string BillingNo
        {
            get;
            set;
        }
    
        public virtual string KuitansiNo
        {
            get;
            set;
        }
    
        public virtual string CurrencyCode
        {
            get;
            set;
        }
    
        public virtual string BusinessAreaCode
        {
            get;
            set;
        }
    
        public virtual string CustomerNo
        {
            get;
            set;
        }
    
        public virtual string SpesNumber
        {
            get;
            set;
        }
    
        public virtual string SONumber
        {
            get;
            set;
        }
    
        public virtual string Salesman
        {
            get;
            set;
        }
    
        public virtual string ChasisNumber
        {
            get;
            set;
        }
    
        public virtual string PONumberSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<int> VersionPOSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> PaymentAmountDC
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> PaymentAmountLC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> paymentDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> version
        {
            get;
            set;
        }
    
        public virtual string flags
        {
            get;
            set;
        }
    
        public virtual string CompanyCodeAI
        {
            get;
            set;
        }

        #endregion

    }
}
