//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02005_TEMP_HS
    {
        #region Primitive Properties
    
        public virtual string GroupingCode
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PaymentDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> TotalPayment
        {
            get;
            set;
        }
    
        public virtual Nullable<int> version
        {
            get;
            set;
        }
    
        public virtual string CompanyCodeAI
        {
            get;
            set;
        }

        #endregion

    }
}
