//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B2BAISERA.Models.EFServer
{
    public partial class EProcEntities : ObjectContext
    {
        public const string ConnectionString = "name=EProcEntities";
        public const string ContainerName = "EProcEntities";
    
        #region Constructors
    
        public EProcEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<CUSTOM_TRANSACTION> CUSTOM_TRANSACTION
        {
            get { return _cUSTOM_TRANSACTION  ?? (_cUSTOM_TRANSACTION = CreateObjectSet<CUSTOM_TRANSACTION>("CUSTOM_TRANSACTION")); }
        }
        private ObjectSet<CUSTOM_TRANSACTION> _cUSTOM_TRANSACTION;
    
        public ObjectSet<CUSTOM_TRANSACTIONDATA> CUSTOM_TRANSACTIONDATA
        {
            get { return _cUSTOM_TRANSACTIONDATA  ?? (_cUSTOM_TRANSACTIONDATA = CreateObjectSet<CUSTOM_TRANSACTIONDATA>("CUSTOM_TRANSACTIONDATA")); }
        }
        private ObjectSet<CUSTOM_TRANSACTIONDATA> _cUSTOM_TRANSACTIONDATA;
    
        public ObjectSet<CUSTOM_TRANSACTIONDATADETAIL> CUSTOM_TRANSACTIONDATADETAIL
        {
            get { return _cUSTOM_TRANSACTIONDATADETAIL  ?? (_cUSTOM_TRANSACTIONDATADETAIL = CreateObjectSet<CUSTOM_TRANSACTIONDATADETAIL>("CUSTOM_TRANSACTIONDATADETAIL")); }
        }
        private ObjectSet<CUSTOM_TRANSACTIONDATADETAIL> _cUSTOM_TRANSACTIONDATADETAIL;
    
        public ObjectSet<CUSTOMIR> CUSTOMIRs
        {
            get { return _cUSTOMIRs  ?? (_cUSTOMIRs = CreateObjectSet<CUSTOMIR>("CUSTOMIRs")); }
        }
        private ObjectSet<CUSTOMIR> _cUSTOMIRs;
    
        public ObjectSet<CUSTOM_S02005_HS> CUSTOM_S02005_HS
        {
            get { return _cUSTOM_S02005_HS  ?? (_cUSTOM_S02005_HS = CreateObjectSet<CUSTOM_S02005_HS>("CUSTOM_S02005_HS")); }
        }
        private ObjectSet<CUSTOM_S02005_HS> _cUSTOM_S02005_HS;
    
        public ObjectSet<CUSTOM_S02005_TEMP_HS> CUSTOM_S02005_TEMP_HS
        {
            get { return _cUSTOM_S02005_TEMP_HS  ?? (_cUSTOM_S02005_TEMP_HS = CreateObjectSet<CUSTOM_S02005_TEMP_HS>("CUSTOM_S02005_TEMP_HS")); }
        }
        private ObjectSet<CUSTOM_S02005_TEMP_HS> _cUSTOM_S02005_TEMP_HS;
    
        public ObjectSet<CUSTOM_S02005_IS> CUSTOM_S02005_IS
        {
            get { return _cUSTOM_S02005_IS  ?? (_cUSTOM_S02005_IS = CreateObjectSet<CUSTOM_S02005_IS>("CUSTOM_S02005_IS")); }
        }
        private ObjectSet<CUSTOM_S02005_IS> _cUSTOM_S02005_IS;
    
        public ObjectSet<CUSTOM_S02005_TEMP_IS> CUSTOM_S02005_TEMP_IS
        {
            get { return _cUSTOM_S02005_TEMP_IS  ?? (_cUSTOM_S02005_TEMP_IS = CreateObjectSet<CUSTOM_S02005_TEMP_IS>("CUSTOM_S02005_TEMP_IS")); }
        }
        private ObjectSet<CUSTOM_S02005_TEMP_IS> _cUSTOM_S02005_TEMP_IS;
    
        public ObjectSet<CUSTOM_S02007> CUSTOM_S02007
        {
            get { return _cUSTOM_S02007  ?? (_cUSTOM_S02007 = CreateObjectSet<CUSTOM_S02007>("CUSTOM_S02007")); }
        }
        private ObjectSet<CUSTOM_S02007> _cUSTOM_S02007;
    
        public ObjectSet<CUSTOM_LOG> CUSTOM_LOG
        {
            get { return _cUSTOM_LOG  ?? (_cUSTOM_LOG = CreateObjectSet<CUSTOM_LOG>("CUSTOM_LOG")); }
        }
        private ObjectSet<CUSTOM_LOG> _cUSTOM_LOG;
    
        public ObjectSet<CUSTOM_USER> CUSTOM_USER
        {
            get { return _cUSTOM_USER  ?? (_cUSTOM_USER = CreateObjectSet<CUSTOM_USER>("CUSTOM_USER")); }
        }
        private ObjectSet<CUSTOM_USER> _cUSTOM_USER;
    
        public ObjectSet<CUSTOMPROPOSALPAYMENT> CUSTOMPROPOSALPAYMENTs
        {
            get { return _cUSTOMPROPOSALPAYMENTs  ?? (_cUSTOMPROPOSALPAYMENTs = CreateObjectSet<CUSTOMPROPOSALPAYMENT>("CUSTOMPROPOSALPAYMENTs")); }
        }
        private ObjectSet<CUSTOMPROPOSALPAYMENT> _cUSTOMPROPOSALPAYMENTs;
    
        public ObjectSet<CUSTOMPO> CUSTOMPOes
        {
            get { return _cUSTOMPOes  ?? (_cUSTOMPOes = CreateObjectSet<CUSTOMPO>("CUSTOMPOes")); }
        }
        private ObjectSet<CUSTOMPO> _cUSTOMPOes;

        #endregion

        #region Function Imports
        public ObjectResult<CUSTOM_S02005_TEMP_IS> sp_PaymentSeraToAI_IS()
        {
            return base.ExecuteFunction<CUSTOM_S02005_TEMP_IS>("sp_PaymentSeraToAI_IS");
        }
        public ObjectResult<CUSTOM_S02005_TEMP_HS> sp_PaymentSeraToAI_HS()
        {
            return base.ExecuteFunction<CUSTOM_S02005_TEMP_HS>("sp_PaymentSeraToAI_HS");
        }
        public ObjectResult<Nullable<int>> sp_UpdateCustomPOStatusPOId(string pONUMBER, string pOSTATUSID)
        {
    
            ObjectParameter pONUMBERParameter;
    
            if (pONUMBER != null)
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", pONUMBER);
            }
            else
            {
                pONUMBERParameter = new ObjectParameter("PONUMBER", typeof(string));
            }
    
            ObjectParameter pOSTATUSIDParameter;
    
            if (pOSTATUSID != null)
            {
                pOSTATUSIDParameter = new ObjectParameter("POSTATUSID", pOSTATUSID);
            }
            else
            {
                pOSTATUSIDParameter = new ObjectParameter("POSTATUSID", typeof(string));
            }
            return base.ExecuteFunction<Nullable<int>>("sp_UpdateCustomPOStatusPOId", pONUMBERParameter, pOSTATUSIDParameter);
        }
        public ObjectResult<spCollectDataProposal_Result> spCollectDataProposal()
        {
            return base.ExecuteFunction<spCollectDataProposal_Result>("spCollectDataProposal");
        }
        public ObjectResult<spCollectDataProposal_Result> spCollectDataPonumber(string propNumber)
        {
    
            ObjectParameter propNumberParameter;
    
            if (propNumber != null)
            {
                propNumberParameter = new ObjectParameter("propNumber", propNumber);
            }
            else
            {
                propNumberParameter = new ObjectParameter("propNumber", typeof(string));
            }
            return base.ExecuteFunction<spCollectDataProposal_Result>("spCollectDataPonumber", propNumberParameter);
        }

        #endregion

    }
}
